name: psl-examples-env
channels:
  - PSLmodels
dependencies:
- python
- pytest>=6.0
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- pip
- pip:
  - pip install git+https://github.com/PSLmodels/Tax-Calculator.git
